"""empty message

Revision ID: 78834bcec50e
Revises: b855574eb681
Create Date: 2025-08-07 09:19:05.415134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78834bcec50e'
down_revision = 'b855574eb681'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('post_comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_post_comentarios_post_id_posts',
            'posts',
            ['post_id'], ['id']
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comentarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
